# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-14 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190423_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(blank=True, default='billingemail@gmail.com', max_length=254, null=True),
        ),
    ]
