# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-23 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190423_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='name',
            field=models.CharField(default='guest', max_length=120, null=True),
        ),
    ]
