# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('t-shirts', 'T-Shirts'), ('shoes', 'Shoes'), ('women gowns', 'Women Gowns'), ('trousers', 'Trousers')], default='T-Shirt', max_length=120),
        ),
    ]
