# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('t-shirts', 'T-Shirts'), ('shoes', 'Shoes'), ('women wears', 'Women Wears'), ('trousers', 'Trousers')], default='T-Shirt', max_length=120),
        ),
    ]
